extends RefCounted
class_name TileCatalog

const TILES := {
	"air": {"name": "Air", "band": "shared", "hardness": INF, "breakable": false, "solid": false, "blocks_light": false, "occlusion": 0.0, "color": Color.TRANSPARENT, "highlight": Color.TRANSPARENT, "value": 0.0, "drops": []},
	"surface_grass": {"name": "Surface Grass", "band": "surface_area", "hardness": 0.7, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.48, "color": Color8(63, 111, 53), "highlight": Color8(139, 173, 74), "value": 0.8, "drops": [{"item": "dirt_clod", "min": 1, "max": 1, "chance": 1.0}]},
	"surface_loam": {"name": "Surface Loam", "band": "surface_area", "hardness": 0.95, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.66, "color": Color8(112, 80, 49), "highlight": Color8(180, 143, 68), "value": 1.0, "drops": [{"item": "dirt_clod", "min": 1, "max": 1, "chance": 1.0}]},
	"surface_root_loam": {"name": "Rootbound Loam", "band": "surface_area", "hardness": 1.15, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.74, "color": Color8(96, 65, 45), "highlight": Color8(148, 112, 58), "value": 1.2, "drops": [{"item": "dirt_clod", "min": 1, "max": 2, "chance": 1.0}]},
	"surface_stone": {"name": "Surface Stone", "band": "surface_area", "hardness": 1.8, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.90, "color": Color8(88, 92, 94), "highlight": Color8(142, 146, 144), "value": 1.8, "drops": [{"item": "stone_chunk", "min": 1, "max": 1, "chance": 1.0}]},
	"loose_dirt": {"name": "Loose Dirt", "band": "standard_caverns", "hardness": 0.75, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.68, "color": Color8(122, 75, 46), "highlight": Color8(168, 111, 60), "value": 1.0, "drops": [{"item": "dirt_clod", "min": 1, "max": 1, "chance": 1.0}]},
	"compacted_dirt": {"name": "Compacted Dirt", "band": "standard_caverns", "hardness": 1.2, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.76, "color": Color8(95, 61, 43), "highlight": Color8(141, 90, 54), "value": 1.4, "drops": [{"item": "dirt_clod", "min": 1, "max": 2, "chance": 1.0}]},
	"soft_stone": {"name": "Soft Stone", "band": "standard_caverns", "hardness": 2.1, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.94, "color": Color8(89, 97, 106), "highlight": Color8(136, 147, 154), "value": 2.2, "drops": [{"item": "stone_chunk", "min": 1, "max": 1, "chance": 1.0}]},
	"copper_ore": {"name": "Copper Ore", "band": "standard_caverns", "hardness": 2.4, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.88, "color": Color8(110, 81, 61), "highlight": Color8(240, 168, 79), "value": 5.5, "drops": [{"item": "copper_nugget", "min": 1, "max": 2, "chance": 1.0}]},
	"hardened_resin": {"name": "Hardened Resin", "band": "colossal_ant_chambers", "hardness": 3.8, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.35, "color": Color8(143, 95, 34), "highlight": Color8(241, 184, 91), "value": 4.0, "drops": [{"item": "resin_shard", "min": 1, "max": 1, "chance": 0.9}]},
	"royal_jelly": {"name": "Royal Jelly", "band": "colossal_ant_chambers", "hardness": 1.0, "breakable": true, "solid": true, "blocks_light": false, "occlusion": 0.10, "color": Color8(240, 211, 94), "highlight": Color8(255, 238, 154), "value": 10.0, "drops": [{"item": "royal_jelly", "min": 1, "max": 1, "chance": 1.0}]},
	"dwarf_granite_brick": {"name": "Dwarf Granite Brick", "band": "colossal_ant_chambers", "hardness": 4.8, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.94, "color": Color8(72, 76, 78), "highlight": Color8(158, 164, 160), "value": 4.4, "drops": [{"item": "stone_chunk", "min": 1, "max": 2, "chance": 1.0}]},
	"dwarf_cut_granite_floor": {"name": "Dwarf Cut Granite Floor", "band": "colossal_ant_chambers", "hardness": 4.4, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.78, "color": Color8(86, 86, 80), "highlight": Color8(190, 178, 122), "value": 4.6, "drops": [{"item": "stone_chunk", "min": 1, "max": 1, "chance": 1.0}]},
	"dwarf_ironbound_block": {"name": "Dwarf Ironbound Block", "band": "colossal_ant_chambers", "hardness": 5.4, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.96, "color": Color8(55, 61, 65), "highlight": Color8(205, 174, 92), "value": 5.4, "drops": [{"item": "stone_chunk", "min": 1, "max": 1, "chance": 0.85}, {"item": "copper_nugget", "min": 1, "max": 1, "chance": 0.18}]},
	"dwarf_rune_block": {"name": "Dwarf Rune Block", "band": "colossal_ant_chambers", "hardness": 5.0, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.86, "color": Color8(68, 62, 72), "highlight": Color8(255, 191, 82), "value": 5.8, "drops": [{"item": "stone_chunk", "min": 1, "max": 1, "chance": 1.0}]},
	"dwarf_iron_platform": {"name": "Dwarf Iron Platform", "band": "colossal_ant_chambers", "hardness": 4.2, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.52, "color": Color8(72, 70, 64), "highlight": Color8(216, 170, 83), "value": 4.0, "drops": [{"item": "stone_chunk", "min": 1, "max": 1, "chance": 0.65}, {"item": "copper_nugget", "min": 1, "max": 1, "chance": 0.12}]},
	"sandstone_block": {"name": "Buried Sandstone", "band": "buried_pyramids", "hardness": 4.4, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.90, "color": Color8(155, 129, 80), "highlight": Color8(210, 179, 106), "value": 4.8, "drops": [{"item": "sandstone_shard", "min": 1, "max": 2, "chance": 1.0}]},
	"pressure_plate": {"name": "Pressure Plate", "band": "buried_pyramids", "hardness": 1.0, "breakable": true, "solid": false, "blocks_light": false, "occlusion": 0.0, "color": Color8(62, 143, 116), "highlight": Color8(112, 206, 177), "value": 1.0, "drops": [{"item": "sandstone_shard", "min": 1, "max": 1, "chance": 0.5}]},
	"cursed_treasure": {"name": "Cursed Treasure", "band": "buried_pyramids", "hardness": 1.8, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.25, "color": Color8(88, 66, 40), "highlight": Color8(255, 214, 107), "value": 14.0, "drops": [{"item": "cursed_relic", "min": 1, "max": 1, "chance": 1.0}]},
	"chest_block": {"name": "Chest", "band": "shared", "hardness": 1.5, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.55, "color": Color8(126, 73, 35), "highlight": Color8(255, 214, 107), "value": 0.0, "drops": []},
	"goblin_timber_wall": {"name": "Goblin Timber Wall", "band": "standard_caverns", "hardness": 1.4, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.72, "color": Color8(92, 58, 34), "highlight": Color8(176, 116, 58), "value": 1.2, "drops": [{"item": "dirt_clod", "min": 1, "max": 1, "chance": 0.45}]},
	"goblin_packed_floor": {"name": "Goblin Packed Floor", "band": "standard_caverns", "hardness": 1.0, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.62, "color": Color8(104, 75, 48), "highlight": Color8(163, 125, 77), "value": 0.8, "drops": [{"item": "dirt_clod", "min": 1, "max": 1, "chance": 0.65}]},
	"goblin_hide_canopy": {"name": "Goblin Hide Canopy", "band": "standard_caverns", "hardness": 0.9, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.45, "color": Color8(84, 85, 48), "highlight": Color8(145, 139, 72), "value": 0.7, "drops": [{"item": "dirt_clod", "min": 1, "max": 1, "chance": 0.35}]},
	"goblin_mossy_brick": {"name": "Goblin Mossy Brick", "band": "standard_caverns", "hardness": 2.2, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.88, "color": Color8(48, 54, 48), "highlight": Color8(91, 112, 68), "value": 1.8, "drops": [{"item": "stone_chunk", "min": 1, "max": 1, "chance": 1.0}]},
	"goblin_plank_platform": {"name": "Goblin Plank Platform", "band": "standard_caverns", "hardness": 1.1, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.50, "color": Color8(94, 58, 35), "highlight": Color8(170, 106, 53), "value": 1.0, "drops": [{"item": "wooden_background_block", "min": 1, "max": 1, "chance": 0.65}]},
	"glow_mushroom_loam": {"name": "Glow Loam", "band": "drow_enclaves", "hardness": 5.0, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.50, "color": Color8(45, 63, 130), "highlight": Color8(85, 214, 210), "value": 6.0, "drops": [{"item": "glow_spore", "min": 1, "max": 2, "chance": 0.85}]},
	"drow_basalt_brick": {"name": "Drow Basalt Brick", "band": "drow_enclaves", "hardness": 5.8, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.92, "color": Color8(36, 44, 86), "highlight": Color8(112, 206, 177), "value": 5.2, "drops": [{"item": "stone_chunk", "min": 1, "max": 2, "chance": 1.0}]},
	"drow_carved_floor": {"name": "Drow Carved Floor", "band": "drow_enclaves", "hardness": 4.9, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.78, "color": Color8(36, 44, 86), "highlight": Color8(85, 214, 210), "value": 5.8, "drops": [{"item": "stone_chunk", "min": 1, "max": 1, "chance": 1.0}]},
	"drow_mushroom_plank": {"name": "Drow Mushroom Plank", "band": "drow_enclaves", "hardness": 2.6, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.55, "color": Color8(106, 67, 136), "highlight": Color8(172, 111, 171), "value": 4.0, "drops": [{"item": "glow_spore", "min": 1, "max": 1, "chance": 0.45}]},
	"drow_silk_canopy": {"name": "Drow Silk Canopy", "band": "drow_enclaves", "hardness": 1.4, "breakable": true, "solid": false, "blocks_light": false, "occlusion": 0.08, "color": Color8(98, 71, 155), "highlight": Color8(160, 112, 220), "value": 3.6, "drops": [{"item": "drow_silk", "min": 1, "max": 1, "chance": 0.9}]},
	"drow_arch_inlay": {"name": "Drow Arch Inlay", "band": "drow_enclaves", "hardness": 6.0, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.90, "color": Color8(62, 55, 119), "highlight": Color8(160, 112, 220), "value": 6.2, "drops": [{"item": "stone_chunk", "min": 1, "max": 2, "chance": 1.0}]},
	"drow_glowglass": {"name": "Drow Glowglass", "band": "drow_enclaves", "hardness": 2.2, "breakable": true, "solid": false, "blocks_light": false, "occlusion": 0.04, "color": Color8(45, 63, 130), "highlight": Color8(85, 214, 210), "value": 7.0, "drops": [{"item": "glow_spore", "min": 1, "max": 1, "chance": 0.8}]},
	"obsidian_ash": {"name": "Obsidian Ash", "band": "abyssal_lava_slums", "hardness": 7.0, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.98, "color": Color8(23, 20, 26), "highlight": Color8(255, 93, 36), "value": 8.0, "drops": [{"item": "obsidian_chip", "min": 1, "max": 1, "chance": 0.9}]},
	"workbench_block": {"name": "Workbench", "band": "shared", "hardness": 2.0, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.60, "color": Color8(120, 72, 34), "highlight": Color8(210, 140, 68), "value": 0.0, "drops": [{"item": "workbench", "min": 1, "max": 1, "chance": 1.0}]},
	"furnace_block": {"name": "Furnace", "band": "shared", "hardness": 3.0, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.82, "color": Color8(66, 60, 60), "highlight": Color8(255, 120, 40), "value": 0.0, "drops": [{"item": "furnace", "min": 1, "max": 1, "chance": 1.0}]},
	"anvil_block": {"name": "Anvil", "band": "shared", "hardness": 4.0, "breakable": true, "solid": true, "blocks_light": true, "occlusion": 0.76, "color": Color8(54, 58, 64), "highlight": Color8(180, 185, 190), "value": 0.0, "drops": [{"item": "anvil", "min": 1, "max": 1, "chance": 1.0}]},
	"solid_dark_block": {"name": "Solid Dark Block", "band": "solid_dark_blocks", "hardness": 9999.0, "breakable": false, "solid": true, "blocks_light": true, "occlusion": 1.0, "color": Color8(5, 6, 17), "highlight": Color8(34, 39, 70), "value": 0.0, "drops": []}
}

static func get_tile(tile_id: String) -> Dictionary:
	return TILES.get(tile_id, TILES.air)

static func is_solid(tile_id: String) -> bool:
	return bool(get_tile(tile_id).solid)

static func is_breakable(tile_id: String) -> bool:
	return bool(get_tile(tile_id).breakable)
